In [1]:
import re
import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/katiegarrett/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [2]:
top_2022 = pd.read_csv('../data/top_2022.csv')
top_2022.head()

,Unnamed: 0,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_is_blocked,...,author_flair_background_color,author_flair_text_color,author_flair_template_id,post_hint,preview,banned_by,crosspost_parent,crosspost_parent_list,url_overridden_by_dest,date
0,0,[],False,eafdrives,NaN,[],NaN,text,t2_5r6aqibp,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-20 01:14:20+00:00
1,1,[],False,Coffeeislife78,NaN,[],NaN,text,t2_119j5kkd,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-04 03:48:08+00:00
2,2,[],False,csswimmer,NaN,[],NaN,text,t2_a3fobm7t,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-24 01:57:41+00:00
3,3,[],False,Irrational-gonzo,NaN,[],NaN,text,t2_107xu5,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-03 19:04:38+00:00
4,4,[],False,InfiniteAvocado412,NaN,[],NaN,text,t2_j6iv5vaq,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-20 23:54:30+00:00

In [3]:
top_2022["combined"] = top_2022["title"].astype(str) + top_2022["selftext"].astype(str)

In [4]:
top_2022["row_id"] = top_2022.index + 1 
print (top_2022.head(10))

   Unnamed: 0 all_awardings  allow_live_comments                author  \
0           0            []                False             eafdrives
1           1            []                False        Coffeeislife78
2           2            []                False             csswimmer
3           3            []                False      Irrational-gonzo
4           4            []                False    InfiniteAvocado412
5           5            []                False   Effective-Fold-1007
6           6            []                False       lunarmovement91
7           7            []                False            rachelques
8           8            []                False              fifidog1
9           9            []                False  Main_Seaworthiness81

   author_flair_css_class author_flair_richtext author_flair_text  \
0                     NaN                    []               NaN
1                     NaN                    []               NaN
2                     NaN                    []               NaN
3                     NaN                    []               NaN
4                     NaN                    []               NaN
5                     NaN                    []               NaN
6                     NaN                    []               NaN
7                     NaN                    []               NaN
8                     NaN                    []               NaN
9                     NaN                    []               NaN

  author_flair_type author_fullname  author_is_blocked  ...  \
0              text     t2_5r6aqibp              False  ...
1              text     t2_119j5kkd              False  ...
2              text     t2_a3fobm7t              False  ...
3              text       t2_107xu5              False  ...
4              text     t2_j6iv5vaq              False  ...
5              text     t2_c2wvoxsj              False  ...
6              text     t2_bjo4x60d              False  ...
7              text     t2_37elbynp              False  ...
8              text     t2_coslhemd              False  ...
9              text     t2_mi5cahye              False  ...

  author_flair_template_id post_hint preview  banned_by  crosspost_parent  \
0                      NaN       NaN     NaN        NaN               NaN
1                      NaN       NaN     NaN        NaN               NaN
2                      NaN       NaN     NaN        NaN               NaN
3                      NaN       NaN     NaN        NaN               NaN
4                      NaN       NaN     NaN        NaN               NaN
5                      NaN       NaN     NaN        NaN               NaN
6                      NaN       NaN     NaN        NaN               NaN
7                      NaN       NaN     NaN        NaN               NaN
8                      NaN       NaN     NaN        NaN               NaN
9                      NaN       NaN     NaN        NaN               NaN

   crosspost_parent_list url_overridden_by_dest                       date  \
0                    NaN                    NaN  2022-05-20 01:14:20+00:00
1                    NaN                    NaN  2022-06-04 03:48:08+00:00
2                    NaN                    NaN  2022-05-24 01:57:41+00:00
3                    NaN                    NaN  2022-06-03 19:04:38+00:00
4                    NaN                    NaN  2022-05-20 23:54:30+00:00
5                    NaN                    NaN  2022-05-20 21:42:41+00:00
6                    NaN                    NaN  2022-05-21 00:01:00+00:00
7                    NaN                    NaN  2022-05-21 00:03:02+00:00
8                    NaN                    NaN  2022-05-20 23:51:43+00:00
9                    NaN                    NaN  2022-05-20 23:42:51+00:00

                                            combined row_id
0  Chaperone at Dance Concert Takes a Left Turn.....      1
1  Interview or Interrogation?This is more of a r...      2
2  Non renewed for not making friendsI found out ...      3
3  Finally quit teaching and got a new job.[removed]      4
4  Performance EvaluationAbout one week left of t...      5
5  Do teachers actually write lesson plans?I donâ€™...      6
6  Iâ€™ve been calling off sick every week for mont...      7
7  Itâ€™s not ALWAYS terribleThis was my first year...      8
8  Confused student teacher about to graduateWhy ...      9
9  I was called and told I had five days to accep...     10

[10 rows x 76 columns]

In [5]:
top_2022_subset = top_2022[['row_id', 'combined']].copy()
#data clean-up
#remove all non-alphabet characters
top_2022_subset['combined'] = top_2022_subset['combined'].str.replace("[^a-zA-Z#]", " ")
#convert to lower-case
top_2022_subset['combined'] = top_2022_subset['combined'].str.casefold()
print (top_2022_subset.head(10))

   row_id                                           combined
0       1  chaperone at dance concert takes a left turn  ...
1       2  interview or interrogation this is more of a r...
2       3  non renewed for not making friendsi found out ...
3       4  finally quit teaching and got a new job  removed
4       5  performance evaluationabout one week left of t...
5       6  do teachers actually write lesson plans i don ...
6       7  i ve been calling off sick every week for mont...
7       8  it s not always terriblethis was my first year...
8       9  confused student teacher about to graduatewhy ...
9      10  i was called and told i had five days to accep...

/var/folders/4_/948td82x7jlf4pz0c4dtqn_00000gn/T/ipykernel_31530/1165315911.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  top_2022_subset['combined'] = top_2022_subset['combined'].str.replace("[^a-zA-Z#]", " ")

In [6]:
df1=pd.DataFrame()
df1['row_id']=['99999999999']
df1['sentiment_type']='NA999NA'
df1['sentiment_score']=0

In [7]:
print('Processing sentiment analysis...')
sid = SentimentIntensityAnalyzer()
t_df = df1
for index, row in top_2022_subset.iterrows():
    scores = sid.polarity_scores(row[1])
    for key, value in scores.items():
        temp = [key,value,row[0]]
        df1['row_id']=row[0]
        df1['sentiment_type']=key
        df1['sentiment_score']=value
        t_df=t_df.append(df1)
#remove dummy row with row_id = 99999999999
t_df_cleaned = t_df[t_df.row_id != '99999999999']
#remove duplicates if any exist
t_df_cleaned = t_df_cleaned.drop_duplicates()
# only keep rows where sentiment_type = compound
t_df_cleaned = t_df[t_df.sentiment_type == 'compound']
print(t_df_cleaned.head(10))

Processing sentiment analysis...
   row_id sentiment_type  sentiment_score
0       1       compound          -0.7595
0       2       compound           0.0553
0       3       compound           0.8711
0       4       compound           0.0000
0       5       compound           0.0000
0       6       compound          -0.4519
0       7       compound          -0.9278
0       8       compound           0.9901
0       9       compound           0.8338
0      10       compound           0.4513

In [8]:
df_output = pd.merge(top_2022, t_df_cleaned, on='row_id', how='inner')
print(df_output.head(10))

   Unnamed: 0 all_awardings  allow_live_comments                author  \
0           0            []                False             eafdrives
1           1            []                False        Coffeeislife78
2           2            []                False             csswimmer
3           3            []                False      Irrational-gonzo
4           4            []                False    InfiniteAvocado412
5           5            []                False   Effective-Fold-1007
6           6            []                False       lunarmovement91
7           7            []                False            rachelques
8           8            []                False              fifidog1
9           9            []                False  Main_Seaworthiness81

   author_flair_css_class author_flair_richtext author_flair_text  \
0                     NaN                    []               NaN
1                     NaN                    []               NaN
2                     NaN                    []               NaN
3                     NaN                    []               NaN
4                     NaN                    []               NaN
5                     NaN                    []               NaN
6                     NaN                    []               NaN
7                     NaN                    []               NaN
8                     NaN                    []               NaN
9                     NaN                    []               NaN

  author_flair_type author_fullname  author_is_blocked  ... preview banned_by  \
0              text     t2_5r6aqibp              False  ...     NaN       NaN
1              text     t2_119j5kkd              False  ...     NaN       NaN
2              text     t2_a3fobm7t              False  ...     NaN       NaN
3              text       t2_107xu5              False  ...     NaN       NaN
4              text     t2_j6iv5vaq              False  ...     NaN       NaN
5              text     t2_c2wvoxsj              False  ...     NaN       NaN
6              text     t2_bjo4x60d              False  ...     NaN       NaN
7              text     t2_37elbynp              False  ...     NaN       NaN
8              text     t2_coslhemd              False  ...     NaN       NaN
9              text     t2_mi5cahye              False  ...     NaN       NaN

  crosspost_parent  crosspost_parent_list  url_overridden_by_dest  \
0              NaN                    NaN                     NaN
1              NaN                    NaN                     NaN
2              NaN                    NaN                     NaN
3              NaN                    NaN                     NaN
4              NaN                    NaN                     NaN
5              NaN                    NaN                     NaN
6              NaN                    NaN                     NaN
7              NaN                    NaN                     NaN
8              NaN                    NaN                     NaN
9              NaN                    NaN                     NaN

                        date  \
0  2022-05-20 01:14:20+00:00
1  2022-06-04 03:48:08+00:00
2  2022-05-24 01:57:41+00:00
3  2022-06-03 19:04:38+00:00
4  2022-05-20 23:54:30+00:00
5  2022-05-20 21:42:41+00:00
6  2022-05-21 00:01:00+00:00
7  2022-05-21 00:03:02+00:00
8  2022-05-20 23:51:43+00:00
9  2022-05-20 23:42:51+00:00

                                            combined row_id sentiment_type  \
0  Chaperone at Dance Concert Takes a Left Turn.....      1       compound
1  Interview or Interrogation?This is more of a r...      2       compound
2  Non renewed for not making friendsI found out ...      3       compound
3  Finally quit teaching and got a new job.[removed]      4       compound
4  Performance EvaluationAbout one week left of t...      5       compound
5  Do teachers actually write lesson plans?I donâ€™...      6       compound
6  Iâ€™ve been calling off sick every week for mont...      7       compound
7  Itâ€™s not ALWAYS terribleThis was my first year...      8       compound
8  Confused student teacher about to graduateWhy ...      9       compound
9  I was called and told I had five days to accep...     10       compound

  sentiment_score
0         -0.7595
1          0.0553
2          0.8711
3          0.0000
4          0.0000
5         -0.4519
6         -0.9278
7          0.9901
8          0.8338
9          0.4513

[10 rows x 78 columns]

In [9]:
df_output[["sentiment_score"]].describe()

       sentiment_score
count       253.000000
mean          0.129436
std           0.701281
min          -0.998300
25%          -0.502300
50%           0.129800
75%           0.833800
max           0.996900

In [11]:
top_2022_final = df_output

In [12]:
top_2022_final['year'] = 2022

In [13]:
top_2022_final.head()

,Unnamed: 0,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_is_blocked,...,banned_by,crosspost_parent,crosspost_parent_list,url_overridden_by_dest,date,combined,row_id,sentiment_type,sentiment_score,year
0,0,[],False,eafdrives,NaN,[],NaN,text,t2_5r6aqibp,False,...,NaN,NaN,NaN,NaN,2022-05-20 01:14:20+00:00,Chaperone at Dance Concert Takes a Left Turn.....,1,compound,-0.7595,2022
1,1,[],False,Coffeeislife78,NaN,[],NaN,text,t2_119j5kkd,False,...,NaN,NaN,NaN,NaN,2022-06-04 03:48:08+00:00,Interview or Interrogation?This is more of a r...,2,compound,0.0553,2022
2,2,[],False,csswimmer,NaN,[],NaN,text,t2_a3fobm7t,False,...,NaN,NaN,NaN,NaN,2022-05-24 01:57:41+00:00,Non renewed for not making friendsI found out ...,3,compound,0.8711,2022
3,3,[],False,Irrational-gonzo,NaN,[],NaN,text,t2_107xu5,False,...,NaN,NaN,NaN,NaN,2022-06-03 19:04:38+00:00,Finally quit teaching and got a new job.[removed],4,compound,0.0000,2022
4,4,[],False,InfiniteAvocado412,NaN,[],NaN,text,t2_j6iv5vaq,False,...,NaN,NaN,NaN,NaN,2022-05-20 23:54:30+00:00,Performance EvaluationAbout one week left of t...,5,compound,0.0000,2022

In [14]:
top_2022_final.to_csv('top_2022_final.csv')