In [1]:
import re
import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/katiegarrett/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [2]:
top_2020 = pd.read_csv('../data/top_2020.csv')
top_2020.head()

,Unnamed: 0,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,...,steward_reports,thumbnail_height,thumbnail_width,url_overridden_by_dest,crosspost_parent,crosspost_parent_list,author_cakeday,distinguished,media_metadata,date
0,0,"[{'award_sub_type': 'GLOBAL', 'award_type': 'g...",True,ToesocksandFlipflops,NaN,[],NaN,text,t2_14l4oa,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-11-17 13:51:29+00:00
1,1,"[{'award_sub_type': 'GLOBAL', 'award_type': 'g...",True,ladyreyreigns,NaN,[],NaN,text,t2_6e7ohgx7,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-20 22:50:55+00:00
2,2,[],True,jamminjfm,NaN,[],NaN,text,t2_14ogve,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-23 17:22:20+00:00
3,3,[],True,Lanilegend,NaN,"[{'e': 'text', 't': 'High School Psychology'}]",High School Psychology,richtext,t2_8zeij,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-06-11 20:42:55+00:00
4,4,"[{'award_sub_type': 'GLOBAL', 'award_type': 'g...",True,magentasummer,NaN,[],NaN,text,t2_6n4w5afu,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-18 20:59:16+00:00

In [3]:
top_2020["combined"] = top_2020["title"].astype(str) + top_2020["selftext"].astype(str)

In [4]:
top_2020["row_id"] = top_2020.index + 1 
print (top_2020.head(10))

   Unnamed: 0                                      all_awardings  \
0           0  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
1           1  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
2           2                                                 []
3           3                                                 []
4           4  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
5           5                                                 []
6           6  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
7           7                                                 []
8           8  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
9           9  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...

   allow_live_comments                author  author_flair_css_class  \
0                 True  ToesocksandFlipflops                     NaN
1                 True         ladyreyreigns                     NaN
2                 True             jamminjfm                     NaN
3                 True            Lanilegend                     NaN
4                 True         magentasummer                     NaN
5                 True         AristaAchaion                     NaN
6                 True         jumpin_jumpin                     NaN
7                 True         Summer-Autumn                     NaN
8                 True             broski548                     NaN
9                 True        tanyavanya1118                     NaN

                            author_flair_richtext       author_flair_text  \
0                                              []                     NaN
1                                              []                     NaN
2                                              []                     NaN
3  [{'e': 'text', 't': 'High School Psychology'}]  High School Psychology
4                                              []                     NaN
5      [{'e': 'text', 't': 'HS Latin [9 years]'}]      HS Latin [9 years]
6                                              []                     NaN
7                                              []                     NaN
8                                              []                     NaN
9                                              []                     NaN

  author_flair_type author_fullname author_patreon_flair  ... thumbnail_width  \
0              text       t2_14l4oa                False  ...             NaN
1              text     t2_6e7ohgx7                False  ...             NaN
2              text       t2_14ogve                False  ...             NaN
3          richtext        t2_8zeij                False  ...             NaN
4              text     t2_6n4w5afu                False  ...             NaN
5          richtext      t2_6r4y8kj                False  ...             NaN
6              text        t2_qgsrn                False  ...             NaN
7              text     t2_70siwh8e                False  ...             NaN
8              text     t2_793ar7k5                False  ...             NaN
9              text        t2_5f1dv                False  ...             NaN

  url_overridden_by_dest  crosspost_parent  crosspost_parent_list  \
0                    NaN               NaN                    NaN
1                    NaN               NaN                    NaN
2                    NaN               NaN                    NaN
3                    NaN               NaN                    NaN
4                    NaN               NaN                    NaN
5                    NaN               NaN                    NaN
6                    NaN               NaN                    NaN
7                    NaN               NaN                    NaN
8                    NaN               NaN                    NaN
9                    NaN               NaN                    NaN

   author_cakeday distinguished  media_metadata                       date  \
0             NaN           NaN             NaN  2020-11-17 13:51:29+00:00
1             NaN           NaN             NaN  2020-07-20 22:50:55+00:00
2             NaN           NaN             NaN  2020-07-23 17:22:20+00:00
3             NaN           NaN             NaN  2020-06-11 20:42:55+00:00
4             NaN           NaN             NaN  2020-07-18 20:59:16+00:00
5             NaN           NaN             NaN  2020-04-15 20:43:55+00:00
6             NaN           NaN             NaN  2020-09-13 14:02:57+00:00
7             NaN           NaN             NaN  2020-07-22 12:27:14+00:00
8             NaN           NaN             NaN  2020-09-13 00:23:57+00:00
9             NaN           NaN             NaN  2020-06-13 21:57:00+00:00

                                            combined row_id
0  I strongly believe that the hatred of remote l...      1
1  I did it. I quit.Iâ€™m still shaking. I wasnâ€™t p...      2
2  "If they wear a BLM shirt every day we should ...      3
3  Admin called and I finally got my 'told you so...      4
4  I have to address this before I lose it at som...      5
5  Am I the only one who gets a bit irked wheneve...      6
6  Finally, for the first time in my 7 year teach...      7
7  MY DISTRICT IS 100% VIRTUAL!!!!My district's o...      8
8  A high schoolers perspectiveAfter reading thro...      9
9  If you don't believe Black Lives Matter, pleas...     10

[10 rows x 81 columns]

In [5]:
top_2020_subset = top_2020[['row_id', 'combined']].copy()
#data clean-up
#remove all non-alphabet characters
top_2020_subset['combined'] = top_2020_subset['combined'].str.replace("[^a-zA-Z#]", " ")
#convert to lower-case
top_2020_subset['combined'] = top_2020_subset['combined'].str.casefold()
print (top_2020_subset.head(10))

   row_id                                           combined
0       1  i strongly believe that the hatred of remote l...
1       2  i did it  i quit i m still shaking  i wasn t p...
2       3   if they wear a blm shirt every day we should ...
3       4  admin called and i finally got my  told you so...
4       5  i have to address this before i lose it at som...
5       6  am i the only one who gets a bit irked wheneve...
6       7  finally  for the first time in my   year teach...
7       8  my district is      virtual    my district s o...
8       9  a high schoolers perspectiveafter reading thro...
9      10  if you don t believe black lives matter  pleas...

/var/folders/4_/948td82x7jlf4pz0c4dtqn_00000gn/T/ipykernel_2557/656616146.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  top_2020_subset['combined'] = top_2020_subset['combined'].str.replace("[^a-zA-Z#]", " ")

In [6]:
df1=pd.DataFrame()
df1['row_id']=['99999999999']
df1['sentiment_type']='NA999NA'
df1['sentiment_score']=0

In [7]:
print('Processing sentiment analysis...')
sid = SentimentIntensityAnalyzer()
t_df = df1
for index, row in top_2020_subset.iterrows():
    scores = sid.polarity_scores(row[1])
    for key, value in scores.items():
        temp = [key,value,row[0]]
        df1['row_id']=row[0]
        df1['sentiment_type']=key
        df1['sentiment_score']=value
        t_df=t_df.append(df1)
#remove dummy row with row_id = 99999999999
t_df_cleaned = t_df[t_df.row_id != '99999999999']
#remove duplicates if any exist
t_df_cleaned = t_df_cleaned.drop_duplicates()
# only keep rows where sentiment_type = compound
t_df_cleaned = t_df[t_df.sentiment_type == 'compound']
print(t_df_cleaned.head(10))

Processing sentiment analysis...
   row_id sentiment_type  sentiment_score
0       1       compound           0.9733
0       2       compound           0.9791
0       3       compound          -0.0772
0       4       compound           0.8819
0       5       compound           0.9666
0       6       compound           0.0000
0       7       compound           0.5719
0       8       compound           0.7930
0       9       compound           0.9594
0      10       compound           0.0516

In [8]:
df_output = pd.merge(top_2020, t_df_cleaned, on='row_id', how='inner')
print(df_output.head(10))

   Unnamed: 0                                      all_awardings  \
0           0  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
1           1  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
2           2                                                 []
3           3                                                 []
4           4  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
5           5                                                 []
6           6  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
7           7                                                 []
8           8  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...
9           9  [{'award_sub_type': 'GLOBAL', 'award_type': 'g...

   allow_live_comments                author  author_flair_css_class  \
0                 True  ToesocksandFlipflops                     NaN
1                 True         ladyreyreigns                     NaN
2                 True             jamminjfm                     NaN
3                 True            Lanilegend                     NaN
4                 True         magentasummer                     NaN
5                 True         AristaAchaion                     NaN
6                 True         jumpin_jumpin                     NaN
7                 True         Summer-Autumn                     NaN
8                 True             broski548                     NaN
9                 True        tanyavanya1118                     NaN

                            author_flair_richtext       author_flair_text  \
0                                              []                     NaN
1                                              []                     NaN
2                                              []                     NaN
3  [{'e': 'text', 't': 'High School Psychology'}]  High School Psychology
4                                              []                     NaN
5      [{'e': 'text', 't': 'HS Latin [9 years]'}]      HS Latin [9 years]
6                                              []                     NaN
7                                              []                     NaN
8                                              []                     NaN
9                                              []                     NaN

  author_flair_type author_fullname author_patreon_flair  ...  \
0              text       t2_14l4oa                False  ...
1              text     t2_6e7ohgx7                False  ...
2              text       t2_14ogve                False  ...
3          richtext        t2_8zeij                False  ...
4              text     t2_6n4w5afu                False  ...
5          richtext      t2_6r4y8kj                False  ...
6              text        t2_qgsrn                False  ...
7              text     t2_70siwh8e                False  ...
8              text     t2_793ar7k5                False  ...
9              text        t2_5f1dv                False  ...

  crosspost_parent crosspost_parent_list  author_cakeday  distinguished  \
0              NaN                   NaN             NaN            NaN
1              NaN                   NaN             NaN            NaN
2              NaN                   NaN             NaN            NaN
3              NaN                   NaN             NaN            NaN
4              NaN                   NaN             NaN            NaN
5              NaN                   NaN             NaN            NaN
6              NaN                   NaN             NaN            NaN
7              NaN                   NaN             NaN            NaN
8              NaN                   NaN             NaN            NaN
9              NaN                   NaN             NaN            NaN

   media_metadata                       date  \
0             NaN  2020-11-17 13:51:29+00:00
1             NaN  2020-07-20 22:50:55+00:00
2             NaN  2020-07-23 17:22:20+00:00
3             NaN  2020-06-11 20:42:55+00:00
4             NaN  2020-07-18 20:59:16+00:00
5             NaN  2020-04-15 20:43:55+00:00
6             NaN  2020-09-13 14:02:57+00:00
7             NaN  2020-07-22 12:27:14+00:00
8             NaN  2020-09-13 00:23:57+00:00
9             NaN  2020-06-13 21:57:00+00:00

                                            combined row_id sentiment_type  \
0  I strongly believe that the hatred of remote l...      1       compound
1  I did it. I quit.Iâ€™m still shaking. I wasnâ€™t p...      2       compound
2  "If they wear a BLM shirt every day we should ...      3       compound
3  Admin called and I finally got my 'told you so...      4       compound
4  I have to address this before I lose it at som...      5       compound
5  Am I the only one who gets a bit irked wheneve...      6       compound
6  Finally, for the first time in my 7 year teach...      7       compound
7  MY DISTRICT IS 100% VIRTUAL!!!!My district's o...      8       compound
8  A high schoolers perspectiveAfter reading thro...      9       compound
9  If you don't believe Black Lives Matter, pleas...     10       compound

  sentiment_score
0          0.9733
1          0.9791
2         -0.0772
3          0.8819
4          0.9666
5          0.0000
6          0.5719
7          0.7930
8          0.9594
9          0.0516

[10 rows x 83 columns]

In [9]:
df_output[["sentiment_score"]].describe()

       sentiment_score
count       919.000000
mean          0.312401
std           0.663240
min          -0.985200
25%          -0.240000
50%           0.562100
75%           0.913600
max           0.999500

In [10]:
top_2020_final = df_output

In [11]:
top_2020_final['year'] = 2020

In [12]:
top_2020_final.head()

,Unnamed: 0,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,...,crosspost_parent_list,author_cakeday,distinguished,media_metadata,date,combined,row_id,sentiment_type,sentiment_score,year
0,0,"[{'award_sub_type': 'GLOBAL', 'award_type': 'g...",True,ToesocksandFlipflops,NaN,[],NaN,text,t2_14l4oa,False,...,NaN,NaN,NaN,NaN,2020-11-17 13:51:29+00:00,I strongly believe that the hatred of remote l...,1,compound,0.9733,2020
1,1,"[{'award_sub_type': 'GLOBAL', 'award_type': 'g...",True,ladyreyreigns,NaN,[],NaN,text,t2_6e7ohgx7,False,...,NaN,NaN,NaN,NaN,2020-07-20 22:50:55+00:00,I did it. I quit.Iâ€™m still shaking. I wasnâ€™t p...,2,compound,0.9791,2020
2,2,[],True,jamminjfm,NaN,[],NaN,text,t2_14ogve,False,...,NaN,NaN,NaN,NaN,2020-07-23 17:22:20+00:00,"""If they wear a BLM shirt every day we should ...",3,compound,-0.0772,2020
3,3,[],True,Lanilegend,NaN,"[{'e': 'text', 't': 'High School Psychology'}]",High School Psychology,richtext,t2_8zeij,False,...,NaN,NaN,NaN,NaN,2020-06-11 20:42:55+00:00,Admin called and I finally got my 'told you so...,4,compound,0.8819,2020
4,4,"[{'award_sub_type': 'GLOBAL', 'award_type': 'g...",True,magentasummer,NaN,[],NaN,text,t2_6n4w5afu,False,...,NaN,NaN,NaN,NaN,2020-07-18 20:59:16+00:00,I have to address this before I lose it at som...,5,compound,0.9666,2020

In [13]:
top_2020_final = top_2020_final[['author', 'created_utc', 'date', 'combined', 'row_id', 'sentiment_score', 'year']]

In [14]:
top_2020_final.head()

,author,created_utc,date,combined,row_id,sentiment_score,year
0,ToesocksandFlipflops,1605621089,2020-11-17 13:51:29+00:00,I strongly believe that the hatred of remote l...,1,0.9733,2020
1,ladyreyreigns,1595285455,2020-07-20 22:50:55+00:00,I did it. I quit.Iâ€™m still shaking. I wasnâ€™t p...,2,0.9791,2020
2,jamminjfm,1595524940,2020-07-23 17:22:20+00:00,"""If they wear a BLM shirt every day we should ...",3,-0.0772,2020
3,Lanilegend,1591908175,2020-06-11 20:42:55+00:00,Admin called and I finally got my 'told you so...,4,0.8819,2020
4,magentasummer,1595105956,2020-07-18 20:59:16+00:00,I have to address this before I lose it at som...,5,0.9666,2020

In [15]:
top_2020_final.to_csv('top_2020_final.csv')